### ISSUE TITLE
why did i obtain this kind of error?

### ISSUE THREAD

**Issue by RR1800** [PierfrancescoSoffritti/Handy#5]
![image](https://user-images.githubusercontent.com/43414878/45762260-9192cf00-bc60-11e8-9a9e-ed435be5922d.png)

**Comment by PierfrancescoSoffritti** [comment]
I don't know, not a lot of info here. Maybe you haven't properly linked the OpenCV libraries.

**Comment by RR1800** [comment]
Yeah, you're right, I actually use the wrong OpenCV libraries. My device uses 32bit OS and instead of using x86 I use x64. Thankyou :)

**Comment by RR1800** [comment]
Btw, do you know how to detect and follow the movement of the hand?
